# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/packages" # Location of the requirements.txt file
    schedule:
      interval: "weekly"
    # If you want to target the specific file
    target-branch: "main" # Replace with your default branch if different

  - package-ecosystem: "pip"
    directory: "/packages" # Location of the requirements-dev.txt file
    schedule:
      interval: "weekly"
    # If you want to target the specific file
    target-branch: "main" # Replace with your default branch if different
