repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (tests/|docs/).*
      - id: end-of-file-fixer
        exclude: (tests/|docs/).*
      - id: check-yaml
        exclude: (tests/|docs/).*
      - id: check-added-large-files
        exclude: (tests/|docs/).*
      - id: check-case-conflict
        exclude: (tests/|docs/).*
      - id: check-merge-conflict
        exclude: (tests/|docs/).*
      - id: check-docstring-first
        exclude: (tests/|docs/).*


  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: (tests/|docs/).*


  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: (tests/|docs/).*


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        exclude: (tests/|docs/).*

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "-c pyproject.toml" ]
        additional_dependencies: [ "toml" ]
